# Generated by Django 2.1.5 on 2022-03-16 22:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
                ('description', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('uniqueName', models.CharField(max_length=3, unique=True)),
                ('picture', models.ImageField(blank=True, upload_to='city_images')),
                ('description', models.CharField(max_length=500)),
                ('slug', models.SlugField(unique=True)),
                ('categories', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='rent_live.Category')),
            ],
            options={
                'verbose_name_plural': 'Cities',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Description', models.CharField(max_length=500)),
                ('Date', models.DateField(auto_now_add=True)),
                ('cleanlinessRating', models.IntegerField(default=0)),
                ('accuracyRating', models.IntegerField(default=0)),
                ('enjoyabilityRating', models.IntegerField(default=0)),
                ('likes', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LettingAgent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=500)),
                ('dateFounded', models.DateField(blank=True, null=True)),
                ('phone', models.CharField(max_length=15)),
                ('email', models.CharField(max_length=50)),
                ('helpfulnessRating', models.IntegerField(default=0)),
                ('promptnessRating', models.IntegerField(default=0)),
                ('qualityRating', models.IntegerField(default=0)),
                ('logo', models.ImageField(blank=True, upload_to='logo_images')),
                ('slug', models.SlugField(unique=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='rent_live.Category')),
                ('city', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='rent_live.City')),
            ],
        ),
        migrations.CreateModel(
            name='Rental_Property',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=500, unique=True)),
                ('description', models.CharField(max_length=500)),
                ('picture', models.ImageField(blank=True, upload_to='property_images/')),
                ('cleanlinessRating', models.IntegerField(default=0)),
                ('accuracyRating', models.IntegerField(default=0)),
                ('enjoyabilityRating', models.IntegerField(default=0)),
                ('price', models.IntegerField(default=0)),
                ('size', models.IntegerField(default=0)),
                ('followers', models.IntegerField(default=0)),
                ('state', models.BooleanField(default=True)),
                ('slug', models.SlugField(unique=True)),
                ('city', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='rent_live.City')),
                ('lettingAgent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='rent_live.LettingAgent')),
            ],
            options={
                'verbose_name_plural': 'Rental_Properties',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datejoined', models.DateField(auto_now_add=True)),
                ('accessibleUser', models.BooleanField(default=False)),
                ('superUser', models.BooleanField(default=False)),
                ('profilePic', models.ImageField(blank=True, upload_to='profile_images')),
                ('totallikes', models.IntegerField(default=0)),
                ('totalComments', models.IntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
